In [3]:
# To perform simulations, randomisations, or statistics, you need to access functions to draw
#random numbers from specic distributions, evaluate the density of a distribution at a given
# point, etc. This is easy to do in NumPy. For example, to sample numbers from a uniform
# distribution U[0,1], use:
import numpy as np
# sample two random numbers from uniform distribution U[0,1]
np.random.random(2)

array([0.70610897, 0.22151951])

In [4]:
# similarly, you can sample integers:
# provide arguments maximum and how many draws
np.random.randint(5, size = 10)

array([0, 3, 3, 1, 3, 2, 2, 2, 1, 0])

In [5]:
np.random.randint(-5, -3, size = 4)

array([-4, -4, -5, -5])

In [7]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [8]:
np.random.shuffle(a)
a

array([2, 3, 0, 1])

In [9]:
# You can sample random values from many common distributions, 
# including a multivariate normal distribution:
# Beta distribution(alpha, beta, size)
np.random.beta(1/2, 1/2, 4)


array([0.61759587, 0.72128014, 0.96727177, 0.96964732])

In [11]:
np.random.standard_normal(size = 3)

array([ 0.54572102,  2.02815969, -0.66108239])

In [12]:
# Normal distribution(mean, standard dev, size)
np.random.normal(10, 0.1, 4)

array([ 9.98903435,  9.97301433, 10.07523613,  9.99286129])

In [13]:
# Multivariate normal(vector of means, covariance matrix, size)
mus = [1, 3] # vector of means
cov = [[1, 0.3], [0.3, 1]] # covariance matrix
np.random.multivariate_normal(mus, cov, 3)

array([[-0.0547197 ,  2.54885733],
       [ 1.61727199,  1.67930533],
       [ 0.41714231,  6.02581073]])

In [14]:
# An interesting fact about computers and random numbers: technically, these should be
#called \pseudo-random" numbers, because they are actually generated using a deterministic|
#yet complicated|algorithm. As we mentioned in earlier, the generation of these numbers
#starts with a seed, which you can set to reproduce exactly the (random!) outcome of a
#simulation. For example, if we sample two numbers from a uniform distribution:
print(np.random.random(1))
print(np.random.random(1))

[0.07308905]
[0.71504234]


In [15]:
# we should always observe different values. However, you can set the seed, and then re-start
# the sequence of random numbers from the top:
np.random.seed(10)
print(np.random.random(1))
print(np.random.random(1))
np.random.seed(10)
print(np.random.random(1))
print(np.random.random(1))
# This is useful in at least two cases. First, suppose that you are running a set 
# of simulations, but that every so often you incur an error. It is difficult to debug the code, as
# the situation triggering the error is rare. In this case, you can set the seed to an arbitrary
# number, run the simulation, and keep changing the number you use to seed the random
# number generator until you are able to reproduce the problem. Now you can solve it, as you
# can reproduce the error as many times as needed.
# Setting a seed is also useful is when you are drawing figures. Suppose that you are
# showing the results of simulations, and that you want to include a figure showing the results
# in your paper. Then, you can set the seed to an arbitrary number, so that while you are
# working on making the figure pretty and clear, re-running the code will yield exactly the
# same results

[0.77132064]
[0.02075195]
[0.77132064]
[0.02075195]
